'use client';
import { useState } from 'react';
import Link from 'next/link';

export default function CasePage() {
  const [en, setEn] = useState(false);
  const t = (zh: string, english: string) => en ? english : zh;
  return <div className="pl2"><header className="pl2-header"><Link href="/">ProofLens / {t('返回核验', 'Open audit')}</Link><button onClick={() => setEn(!en)}>{en ? '中文' : 'English'}</button></header>
    <main className="pl2-case">
      <p className="pl2-eyebrow">PRODUCT CASE · RESEARCH MVP · SEPTEMBER 2026</p>
      <h1>{t('一次没有证明增益的实验，如何改变产品。', 'An experiment without a demonstrated gain changed the product.')}</h1>
      <p className="pl2-lead">{t('面向研究 Agent 的财务证据核验服务。达鸿儒 / Hongru Da，产品研究与设计，AI 辅助实现与评测。', 'A financial-evidence verification service for research agents. Hongru Da: product research and design, with AI-assisted implementation and evaluation.')}</p>
      <div className="pl2-notice">{t('交付的是可运行、可复现的研究型 MVP。模型角色问卷不是真人研究；目前没有市场采用、收入或稳健的效率提升证据。', 'A runnable, reproducible research MVP. Model-role questionnaires are not human research. Market adoption, revenue and robust efficiency gains remain unproven.')}</div>
      <section className="pl2-panel"><h2>01 · {t('问题从哪里来', 'Where the problem came from')}</h2><p>{t('在本人历史投研任务中，反复出现跨 Agent 复核利润口径、追问原始来源和桥接季度数字的工作。对 8 月记录的回溯确认了 12 条相关原话，来自 8 个任务；这是一个使用者的工作证据，不是多客户市场规模证明。', 'Historical investment-research tasks repeatedly involved cross-agent reconciliation of profit definitions, primary sources and quarterly figures. Twelve relevant requests across eight tasks were verified in an August history review: evidence from one user, not proof of market size.')}</p></section>
      <section className="pl2-panel"><h2>02 · {t('产品取舍', 'Product choices')}</h2><p>{t('直接用户是能调用工具的研究 Agent。服务返回逐主张结论、原文、报告期、会计口径和恢复动作；网页用于演示与复核。', 'The direct user is a tool-using research agent. The service returns claim-level decisions, quotations, reporting periods, accounting bases and recovery actions. The website supports demonstrations and review.')}</p><ul><li>{t('只使用登记的一手资料片段，缺证时停止，不编造来源。', 'Use registered primary-source excerpts; stop when evidence is missing.')}</li><li>{t('不用单一可信度总分：数值相近、期间错配和推断缺证是不同问题。', 'No aggregate trust score: similar numbers, period mismatches and unsupported inference are different failures.')}</li><li>{t('P0 是 REST / MCP 契约、证据定位、失败封闭和预算；暂不做交易、任意网页抓取或付费订阅。', 'P0 covers REST/MCP contracts, evidence locations, fail-closed behavior and budgets. Trading, arbitrary web crawling and subscriptions are out of scope.')}</li></ul></section>
      <section className="pl2-panel"><h2>03 · {t('先检验增量价值', 'Test incremental value first')}</h2><p>{t('同模型、同检索资料、同最终判断要求，6 个配对任务共 24 条合成主张。接入前后最终标签都是 24/24，证据合格任务都是 5/6。', 'With the same model, retrieved material and final-answer instructions, six paired tasks contained 24 synthetic claims. Both workflows reached 24/24 label agreement and 5/6 evidence-qualified tasks.')}</p><div className="pl2-table-wrap"><table><thead><tr><th>{t('指标', 'Metric')}</th><th>{t('普通流程', 'Baseline')}</th><th>+ ProofLens</th></tr></thead><tbody><tr><td>{t('证据合格任务', 'Evidence-qualified tasks')}</td><td>5 / 6</td><td>5 / 6</td></tr><tr><td>{t('中位耗时', 'Median latency')}</td><td>8.688 s</td><td>25.792 s</td></tr><tr><td>{t('全部任务估算费用', 'Estimated total cost')}</td><td>$0.035121</td><td>$0.114122</td></tr></tbody></table></div><p>{t('核心质量没有测出提升，完整链路却更慢、更贵。问卷中的偏好不能推翻这次行为结果。', 'No core quality gain was observed, while the full workflow was slower and more expensive. Questionnaire preferences cannot override this behavioral result.')}</p></section>
      <section className="pl2-panel"><h2>04 · {t('失败推动了什么变化', 'What the failures changed')}</h2><ol><li>{t('检索遗漏季度实际值：加入弱化待核验数字的第二检索通道，并保留财务短语信息。', 'A missing quarterly actual prompted a value-deemphasized retrieval query and financial-phrase features.')}</li><li>{t('模型的减法输入顺序和结果矛盾：改为命名事实操作数，由程序计算并核对引用中的数值。', 'Inconsistent subtraction inputs prompted named fact operands, server-side arithmetic and cited-value checks.')}</li><li>{t('保留模型结论与复核标注的区别；新增独立复核标注及带标注的 JSON 导出。', 'Keep model judgments separate from review labels, and export both without treating a review as new evidence.')}</li></ol><p>{t('旧失败案例是回归测试，新题是同一来源家族中的新增主张。任何回归修复都不能自动写成新的市场增益。最新逐题记录与边界见下载报告。', 'Known failures are regression tests; fresh claims still belong to the same source families. Regression fixes do not establish new market value. See the downloadable report for item-level results and limits.')}</p></section>
      <p>{t('本轮修复：8/8 回归标签一致；同来源家族的新增主张为 10/12，剩余两处失败不隐藏。', 'This iteration: 8/8 regression labels matched; fresh claims from the same source families reached 10/12. The two remaining failures are retained.')}</p>
      <section className="pl2-panel"><h2>05 · {t('研究与作品集证据', 'Research and portfolio evidence')}</h2><p>{t('1024 份有效模型角色问卷来自四个模型、两家供应商，真人数为 0。120 条较早的合成诊断中标签一致 115/120，文档留出为 30/32；不把这些样本称为独立人工黄金集。', '1,024 valid model-role questionnaires came from four models and two providers, with zero human respondents. An earlier 120-claim synthetic diagnostic reached 115/120 label agreement and 30/32 on a document holdout; this is not an independent human-labeled gold set.')}</p><p><Link href="/reports/final-report.md" prefetch={false} download>{t('下载结项报告', 'Download the final report')}</Link> · <Link href="/reports/paired-report.md" prefetch={false} download>{t('阅读配对实验原始结论', 'Read the original paired-study findings')}</Link> · <Link href="/demo.mp4" prefetch={false}>{t('两分钟演示视频', 'Two-minute demonstration')}</Link></p></section>
      <section className="pl2-panel"><h2>06 · {t('下一阶段的门槛', 'The next evidence gate')}</h2><p>{t('先观察陌生调用方能否自主选择和使用工具，再比较合格完成率、完整链路成本与耗时。未来资料更新、真实调用方持续使用、独立人工语义标注和生产 SLA 不包含在当前研究型结项范围。', 'Next, observe whether unfamiliar callers independently select and use the tool, then compare qualified completion, end-to-end cost and latency. Ongoing data updates, sustained customer usage, independent human entailment labels and production SLAs are outside this research-MVP release.')}</p></section>
    </main></div>;
}
